spring:
  application:
    name: auth-service
  jpa:
    databasePlatform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddlAuto: update
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:db_user}?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: ENC(rCbck2Firfg00339kaDGVA==)
server:
  port: 3001

eureka:
  client:
  serviceUrl:
    defaultZone: http://localhost:8761/eureka/

security:
  oauth2:
    client:
      clientId: client
      clientSecret: ENC(48mMvLaMDImeOJFUE/DT0ufm7y9Rcdn/)
      accessTokenValiditySeconds: 18000
      refreshTokenValiditySeconds: 18000
encrypt:
  keyStore:
    alias: jwt
    password: ENC(TQVu0i9dxQgQDOo19OSnKg==)
