service:
  order: 192.168.196.140
  product: 192.168.196.106

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri:
            http://localhost:3001/
          predicates:
            - Path=/oauth/**, /auth/**
        - id: user-service
          uri:
            http://localhost:3002/
          predicates:
            - Path=/user/**
        - id: product-service
          uri:
            http://${service.product}:8000/
          predicates:
            - Path=/product/**, /line/**, /branch/**, /inventory/**, /discount/**, /review/**, /category/**
        - id: order-service
          uri:
            http://${service.order}:8080/
          predicates:
            - Path=/order/**, /cart/**
        - id: address-service
          uri:
            http://localhost:3003/
          predicates:
            - Path=/address/**

server:
  port: ${SERVER_PORT:8762}
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/