security:
  oauth2:
      resource:
        userInfoUri: http://localhost:3001/auth/user

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: user-service
  jpa:
    databasePlatform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddlAuto: update
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:db_user}?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: root
  mail:
    host: smtp.gmail.com
    username: duc.trantrung99@gmail.com
    password: bvxedzgjcmmmmweq
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 3002

eureka:
  client:
  serviceUrl:
    defaultZone: http://localhost:8761/eureka/


ui:
  url: http:localhost:8888

passwordResetTokenValidityHours: 24
