service:
    hostname:
      discovery: 192.168.196.207
      auth: 192.168.196.207
      mysql: ${MYSQL_HOST:192.168.196.207}
      ui: localhost


security:
  oauth2:
    resource:
      userInfoUri: http://${service.hostname.auth}:8900/auth/user

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: user-service
  jpa:
    databasePlatform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddlAuto: update
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${service.hostname.mysql}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:db_user}?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: ENC(T5/NKcOjFiYB/01F1oASPw==)
  mail:
    host: smtp.gmail.com
    username: duc.trantrung99@gmail.com
    password: ENC(O55yp9uj/S7myBJKQJZh1jwosoyyY2s+HUscOxVaozc=)
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8901

eureka:
  client:
    serviceUrl:
      defaultZone: http://${service.hostname.discovery}:8761/eureka/


ui:
  url: http://${service.hostname.ui}:3000

passwordResetTokenValidityHours: 24
